import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { getServerSession } from "next-auth";

import LoginBtn from "./LoginBtn";
import { LogOutBtn } from "./LogOutBtn";

import { authOptions } from "@/pages/api/auth/[...nextauth]";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)
  if (session) {
    console.log(session)
  }
  return (
    <html lang="en">
      <body>
        <div className="navbar">
          <Link href="/" className="logo">Appleforum</Link>
          <Link href="/list">List</Link>
          <Link href="/write">new</Link>
          {
            session
              ? <span>{session.user.name} {session.user.email}
              <img className="imgLogo" src={session.user.image}></img><LogOutBtn /> </span>
              : <LoginBtn></LoginBtn>
          }
        </div>
        {children}
      </body>
    </html>
  );
}
